# Generated by Django 3.1.5 on 2021-01-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_store', models.CharField(max_length=100, verbose_name='name')),
                ('rif_store', models.CharField(blank=True, max_length=15, verbose_name='rif')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='description')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('logo_store', models.ImageField(blank=True, upload_to='store', verbose_name='logo')),
                ('banner_store', models.ImageField(blank=True, upload_to='store', verbose_name='banner')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
            },
        ),
    ]
