# Generated by Django 3.1.5 on 2021-01-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, verbose_name='location')),
                ('municipality', models.CharField(max_length=100, verbose_name='municipality')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('addres', models.CharField(blank=True, max_length=200, verbose_name='addres')),
                ('postal_code', models.IntegerField(blank=True, null=True, verbose_name='postal code')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='stores.store')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
    ]
