# Generated by Django 3.1.5 on 2021-01-19 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=100, verbose_name='state'),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_social_media', models.CharField(max_length=50, verbose_name='social media')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialmedias', to='stores.store')),
            ],
            options={
                'verbose_name': 'social media',
                'verbose_name_plural': 'social medias',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_phone', models.CharField(max_length=11, verbose_name='cell phone')),
                ('local_phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='local phone')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='stores.store')),
            ],
            options={
                'verbose_name': 'phone',
                'verbose_name_plural': 'phones',
            },
        ),
    ]
