# Generated by Django 3.1.5 on 2021-01-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20210118_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='banner_store',
            field=models.ImageField(blank=True, upload_to='store/banner', verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo_store',
            field=models.ImageField(blank=True, upload_to='store/logo', verbose_name='logo'),
        ),
    ]
