# Generated by Django 3.1.5 on 2021-01-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20210119_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'social media', 'verbose_name_plural': 'social media'},
        ),
    ]
