# Generated by Django 3.1.5 on 2021-01-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20210119_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='type_phone',
            field=models.CharField(default='cell phone', max_length=50, verbose_name='type phone'),
        ),
    ]
